### ISSUE TITLE
Improve Entropy Pool

### ISSUE THREAD

**Issue by unprovable** [abderraouf-adjal/ArduinoSpritzCipher#5]
Hello! 
So, a fixed entropy pool in a PRNG is a bad idea, as the PRNG will give precisely the same output every time it is reset (which can happen quite a bit with embedded systems, let's be honest). In short, it gives a random number set that can be rainbow tabled with high precision, which would potentially compromise the encryption relying on this random number generation.
To fix this, I've done some testing on Arduinos that might help? Here is a link: https://medium.com/@LargeCardinal/random-numbers-on-the-arduino-97f325820284
I would recommend using the WDT Jitter _and_ some other source such as the thermal noise on A8. If you use this as the initial entropy pool, it would improve the situation considerably. :D 
I'd write a patch, but I'm currently up to my eyeballs in work, so it would take some time for me to do, but getting fair bits that are perperly random for your entropy pool shouldn't be too hard. 
**NB** - this might add a startup lag to the device, so you may with to have this off by default, turned on if it's important? We have to be realistic about device startup times, of course. :)
Happy to answer any questions! 
Cheers, M.

**Comment by abderraouf-adjal** [comment]
Hi,

ArduinoSpritzCipher doesn't have any function to get entropy. The library act like a dump machine you input all the data (keys, entropy, ...).

The examples are just examples to how input a data and get the output.

Getting entropy in micro-controllers is a wide and a wild topic, so how to get entropy is the **library user** job not the **library job** (ArduinoSpritzCipher v1.0.3). Because the user might use it in a micro-controllers that has a hardware entropy sensor inside, or might not, so user take care of it by attaching a hardware with the micro-controllers for example.

I hope you get the philosophy about why I didn't want the library to take care of getting entropy.

**Comment by abderraouf-adjal** [comment]
@unprovable 
This is the 2nd confusion about the entropy in ArduinoSpritzCipher.
I'm including the answer (which is: Not the library job.) with the next version in the `README.md` notes and in the example of using the library code comments.

Thank you for the issues discovery. If you have any question, please ask.

**Comment by unprovable** [comment]
Yeah, that's fine by me :) So long as it's clear that you're leaving it up to the lib-user and this is clear, then it's up to them. Happy to close this if you are!

**Comment by abderraouf-adjal** [comment]
I'll close it after few days so the social media traffic understand the issue.
For the documentary: I'm willing to add/edit the notes.

**Comment by abderraouf-adjal** [comment]
@unprovable Check the latest commit (07f341c).

**Comment by abderraouf-adjal** [comment]
## Issue update:
A new release (**v1.0.4**) is out.
Improving the existing comments about the entropy; and recommending to read <README.md>.
