### ISSUE TITLE
spritz_random32(spritz_ctx *ctx) - faster?

### ISSUE THREAD

**Issue by RobTillaart** [abderraouf-adjal/ArduinoSpritzCipher#8]
expect some performance gain from this implementation as it does 50% less shifts and no casting
however it might be that the bytes are ordered differently (for randomness that should not matter...?)
```cpp
uint32_t spritz_random32(spritz_ctx *ctx)
{
  uint32_t rv = drip(ctx);
  for (uint8_t i = 0; i < 3; i++)
 {
    rv <<= 8;
   rv |= drip(ctx);
 }
 return rv;
}
```
----
probably even faster when using an union of an uint32_t and an array of 4 bytes.
https://en.cppreference.com/w/cpp/language/union

```cpp
uint32_t spritz_random32(spritz_ctx *ctx)
{
  union
  {
    uint32_t rv;
    uint8_t ar[4];
  } u;
  for (uint8_t i = 0; i < 4; i++)
 {
    u.ar[i] = drip(ctx);
 }
 return u.rv;
}
```

**Comment by abderraouf-adjal** [comment]
Hello again,
The assembler show the current code is better in both cases optimized and non-optimized: <https://godbolt.org/z/qen7fG>

The union version have more stack pop push instructions.
Your proposal don't have less shifts, it's the same amount of shifts but smaller code size, but slower because of the small loop addition. Notice it will loop 4 time a code that will take more time than in-lining the loop.

The are optimizing instruction that convert loops to direct code to avoid `i++`.

However, I will change the usage of `spritz_random8()` in `spritz_random32()` to `drip()` for better in-lining.

**Comment by RobTillaart** [comment]
Fair enough

> However, I will change the usage of spritz_random8() in spritz_random32() to drip() for better in-lining.
good improvement

**Comment by abderraouf-adjal** [comment]
Is it okay to close this?

**Comment by abderraouf-adjal** [comment]
Done: <https://github.com/abderraouf-adjal/ArduinoSpritzCipher/commit/8ecef2fa8555451230eec7ec209a41b4c746c245>
I will also close this if you don't have more comments.
