### ISSUE TITLE
#ifdef SPRITZ_WIPE_TRACES_PARANOID

### ISSUE THREAD

**Issue by RobTillaart** [abderraouf-adjal/ArduinoSpritzCipher#9]
Think this paranoid code can be much simpler, smaller and probably faster
```cpp
  d |= d >> 1; /* |_|_|_|_|_|_|S|D| `D |= S` */
  d |= d >> 2; /* |_|_|_|_|_|S|_|D| */
  d |= d >> 3; /* |_|_|_|_|S|_|_|D| */
  d |= d >> 4; /* |_|_|_|S|_|_|_|D| */
  d |= d >> 5; /* |_|_|S|_|_|_|_|D| */
  d |= d >> 6; /* |_|S|_|_|_|_|_|D| */
  d |= d >> 7; /* |S|_|_|_|_|_|_|D| */
  d &= 1;      /* |0|0|0|0|0|0|0|D| Zero all bits except LSB */
```

```cpp
 d = (d !=  0) : 1 : 0;
```

**Comment by abderraouf-adjal** [comment]
Hello,
As I write in the comments:

> // It may be possible to use `d=!!d;` for performance, But audit the assembly code first.

So I did a quick assembly analysis on AVR, ARM, x86: <https://godbolt.org/z/xzebGP>

I tried the quick way in two variants, one that enables compiler optimization `-Os` and one don't `-O0`.

## **Result**:  
It's okay to do direct assignment **ONLY IF THE OPTIMIZATION IS OFF**, otherwise the compiler will remove the related code because it think it's useless. tell me if I did assembly analysis mistake because this quarantine is missing with brain :laughing:.
I will consider doing direct assignment as in comments and your issue, also note that `SPRITZ_WIPE_TRACES_PARANOID` is off by default.

Thanks.

**Comment by abderraouf-adjal** [comment]
Edit: `ONLY IF THE OPTIMIZATION IS OFF` not `ONLY IF THE OPTIMIZATION IS ON`.

**Comment by RobTillaart** [comment]
Definitely no expert in assembly
 
From what I see (ARM GCC 8.2) are no branches that imply  different code paths (= code timing) 

AVR GCC 4.5.4. has a different code path length at the end where the return value is decided.   
```d = (d != 0U) ? 1U : 0U;```
3 steps in case d == 0 and 4 steps if d == 1
these path lengths do show if string match or not.

X86-64 gcc 10.2 shows no different code path lengths

my 2 cents ...

**Comment by abderraouf-adjal** [comment]
I will add ` d = (d !=  0) : 1 : 0;` or similar one the code and keep the shifting if the optimization can't go off.
Note that this is not important unless you are really paranoid about 1 byte staying in RAM. it's a very astronomic scenario.

**Comment by abderraouf-adjal** [comment]
Done: <https://github.com/abderraouf-adjal/ArduinoSpritzCipher/commit/8ecef2fa8555451230eec7ec209a41b4c746c245>
I will close this if you don't have more comments
